In [2]:
# Import the required libraries
import torch
import torchvision
from torchvision.io import read_image
from torchvision.utils import draw_bounding_boxes
from PIL import Image, ImageFont, ImageDraw 
from tkinter import *
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont



Note: you may need to restart the kernel to use updated packages.


In [29]:

# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000059.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [5718,3358,6035,4134]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [2520,4515,3278,4633]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())

bbox2= [4256,4134,5428,4279]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(5600, 3200),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(2500, 4300),text= "Sealed Crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(4200, 3900),text= "Delamination", fill=(255, 0, 0),font=myFont,)


img.show()

tensor([5718, 3358, 6035, 4134], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([2520, 4515, 3278, 4633], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([4256, 4134, 5428, 4279], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [32]:


# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000088.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [4163,4524,6235,4903]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [2454,4212,2637,4468]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())

bbox2= [5485,3191,5880,4391]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(4100,4400),text= "Patch", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(2400,4000),text= "Sealed Crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(5400,2900),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()

tensor([4163, 4524, 6235, 4903], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([2454, 4212, 2637, 4468], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([5485, 3191, 5880, 4391], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [39]:

# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000167.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [2206,4093,5155,4744]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [5883,3024,6387,4704]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())

bbox2= [4276,3094,4464,3689]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(2200,3900),text= "Sealed Crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(5800,2800),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(4200,2800),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()


tensor([2206, 4093, 5155, 4744], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([5883, 3024, 6387, 4704], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([4276, 3094, 4464, 3689], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [38]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000117.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [2273,4730,2537,5174]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [750,2971,1139,4198]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(2200,4500),text= "Sealed Crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(750,2700),text= "Road Sign", fill=(255, 0, 0),font=myFont,)



img.show()



tensor([2273, 4730, 2537, 5174], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([ 750, 2971, 1139, 4198], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [41]:

# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000229.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [4295,3365,4512,4044]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [5167,3326,5353,4112]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())

bbox2= [629,5270,2101,5446]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

bbox3= [2235,4797,4156,5028]
bbox3 = torch.tensor(bbox3, dtype=torch.int)
print(bbox3)
print(bbox3.size())
bbox3 = bbox3.unsqueeze(0)
print(bbox3.size())

# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox3, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(4200,3100),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(5100,3100),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(630,5100),text= "Transverse Crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(2200,4500),text= "Transverse Crack", fill=(255, 0, 0),font=myFont,)




img.show()



tensor([4295, 3365, 4512, 4044], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([5167, 3326, 5353, 4112], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([ 629, 5270, 2101, 5446], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([2235, 4797, 4156, 5028], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [42]:

# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000238.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [2448,3204,2656,3856]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [2184,4754,4656,5022]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())

bbox2= [2536,4287,3998,4381]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(2400,2900),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(2100,4500),text= "Transverse Crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(2500,4000),text= "Transverse Crack", fill=(255, 0, 0),font=myFont,)


img.show()



tensor([2448, 3204, 2656, 3856], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([2184, 4754, 4656, 5022], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([2536, 4287, 3998, 4381], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [43]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0001_000008.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [4686,2807,5438,4183]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [754,4492,2263,5303]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(4600,2600),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(760,4200),text= "Alligator Crack", fill=(255, 0, 0),font=myFont,)



img.show()



tensor([4686, 2807, 5438, 4183], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([ 754, 4492, 2263, 5303], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [44]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0001_000064.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [2297,4220,2702,4899]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [5364,2964,5871,4185]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(2200,4000),text= "Sealed crack", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(5300,2700),text= "Road Sign", fill=(255, 0, 0),font=myFont,)



img.show()




tensor([2297, 4220, 2702, 4899], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([5364, 2964, 5871, 4185], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [45]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0001_000130.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [3497,4981,5773,5909]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(3400,4800),text= "Sealed crack", fill=(255, 0, 0),font=myFont,)



img.show()



tensor([3497, 4981, 5773, 5909], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [2]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000059.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [5876.5,3358,5876.5,4134]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(5600, 3200),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()

/var/folders/2j/jr2kzq913ndg55h4cvdv9tn40000gn/T/ipykernel_46782/3360225218.py:8: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  bbox = torch.tensor(bbox, dtype=torch.int)


tensor([5876, 3358, 5876, 4134], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [3]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000088.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)


bbox2= [5682.5,3191,5682.5,4391]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

# draw bounding box on the input image

img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(5400,2900),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()

/var/folders/2j/jr2kzq913ndg55h4cvdv9tn40000gn/T/ipykernel_46782/2907390083.py:9: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  bbox2 = torch.tensor(bbox2, dtype=torch.int)


tensor([5682, 3191, 5682, 4391], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [4]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000167.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)



bbox1= [6135,3024,6135,4704]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())

bbox2= [4370,3094,4370,3689]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())

# draw bounding box on the input image

img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)

I1.text(xy=(5800,2800),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(4200,2800),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()

tensor([6135, 3024, 6135, 4704], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([4370, 3094, 4370, 3689], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [6]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000117.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)



bbox1= [944.5,2971,944.5,4198]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())



# draw bounding box on the input image

img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)

I1.text(xy=(750,2700),text= "Road Sign", fill=(255, 0, 0),font=myFont,)



img.show()

/var/folders/2j/jr2kzq913ndg55h4cvdv9tn40000gn/T/ipykernel_46782/475997832.py:10: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  bbox1 = torch.tensor(bbox1, dtype=torch.int)


tensor([ 944, 2971,  944, 4198], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [7]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000229.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [4403.5,3365,4403.5,4044]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

bbox1= [5260,3326,5260,4112]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(4200,3100),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
I1.text(xy=(5100,3100),text= "Road Sign", fill=(255, 0, 0),font=myFont,)




img.show()



/var/folders/2j/jr2kzq913ndg55h4cvdv9tn40000gn/T/ipykernel_46782/1435682309.py:8: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  bbox = torch.tensor(bbox, dtype=torch.int)


tensor([4403, 3365, 4403, 4044], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])
tensor([5260, 3326, 5260, 4112], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [9]:

# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000238.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [2552,3204,2552,3856]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())

# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(2400,2900),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()

tensor([2552, 3204, 2552, 3856], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [11]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0001_000008.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)

bbox = [5062,2807,5062,4183]
bbox = torch.tensor(bbox, dtype=torch.int)
print(bbox)
print(bbox.size())
bbox = bbox.unsqueeze(0)
print(bbox.size())




# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(4600,2600),text= "Road Sign", fill=(255, 0, 0),font=myFont,)


img.show()

tensor([5062, 2807, 5062, 4183], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [12]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0001_000064.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)



bbox1= [5617.5,2964,5617.5,4185]
bbox1 = torch.tensor(bbox1, dtype=torch.int)
print(bbox1)
print(bbox1.size())
bbox1 = bbox1.unsqueeze(0)
print(bbox1.size())



# draw bounding box on the input image
img=draw_bounding_boxes(img, bbox1, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(5300,2700),text= "Road Sign", fill=(255, 0, 0),font=myFont,)



img.show()

/var/folders/2j/jr2kzq913ndg55h4cvdv9tn40000gn/T/ipykernel_46782/1883196307.py:10: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  bbox1 = torch.tensor(bbox1, dtype=torch.int)


tensor([5617, 2964, 5617, 4185], dtype=torch.int32)
torch.Size([4])
torch.Size([1, 4])


In [ ]:
# read input image
img = read_image('/Users/kashvi/Downloads/1907/Images/pano_0000_000088.jpg')

# bounding box in (xmin, ymin, xmax, ymax) format
# top-left point=(xmin, ymin), bottom-right point = (xmax, ymax)


bbox2= [5682.5,3191,5682.5,4391]
bbox2 = torch.tensor(bbox2, dtype=torch.int)
print(bbox2)
print(bbox2.size())
bbox2 = bbox2.unsqueeze(0)
print(bbox2.size())


# draw bounding box on the input image

img=draw_bounding_boxes(img, bbox2, width=20, colors=(255,0,0))

# transform it to PIL image and display
img = torchvision.transforms.ToPILImage()(img)

#Label 

myFont = ImageFont.truetype('Arial.ttf',90)
I1 = ImageDraw.Draw(img)
I1.text(xy=(5400,2900),text= "Road Sign", fill=(255, 0, 0),font=myFont,)
